# Base configs
baseurl: "http://baroquerock.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "photography by tatiana gaponova"
author: "tatiana gaponova"
header:
 title: "photography"
 subtitle: "by tatiana gaponova"
footer:
 name: "hi, i am tatiana"
social_urls:
  instagram: "https://www.instagram.com/baroquerock"
  github: "https://www.github.com/baroquerock"
